on: push

jobs:
  Chocolatey:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Choco Auth to 
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: apikey --key ${{ secrets.chocolatey_apikey }} --source https://push.chocolatey.org/
      -
        name: Choco pack Standalone-Windows-STIG
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: pack ./Standalone-Windows-STIG/Standalone-Windows-STIG.nuspec configuration=release --outputdirectory ./
      -
        name: Choco push Standalone-Windows-STIG
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: push ./Standalone-Windows-STIG/Standalone-Windows-STIG.1.0.0.nupkg
      -
        name: Choco pack Standalone-Windows-Server-STIG
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: pack ./Standalone-Windows-Server-STIG/Standalone-Windows-Server-STIG.nuspec configuration=release --outputdirectory ./
      -
        name: Choco push Standalone-Windows-Server-STIG
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: push ./Standalone-Windows-Server-STIG/Standalone-Windows-Server-STIG.1.0.0.nupkg
      -
        name: Choco pack Windows-Optimize-Debloat
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: pack ./Windows-Optimize-Debloat/Windows-Optimize-Debloat.nuspec configuration=release --outputdirectory ./
      -
        name: Choco push Windows-Optimize-Debloat
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: push ./Windows-Optimize-Debloat/Windows-Optimize-Debloat.1.0.0.nupkg
      -
        name: Choco pack Windows-Optimize-Harden-Debloat
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: pack ./Windows-Optimize-Harden-Debloat/Windows-Optimize-Harden-Debloat.nuspec configuration=release --outputdirectory ./
      -
        name: Choco push Windows-Optimize-Harden-Debloat
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: push ./Windows-Optimize-Harden-Debloat/Windows-Optimize-Harden-Debloat.1.0.0.nupkg configuration=release --outputdirectory ./
      -
        name: Choco pack nethor
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: pack ./nethor/nethor.nuspec configuration=release --outputdirectory ./ 
      -
        name: Choco push nethor
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: push ./nethor/nethor.2022.0.0.nupkg
